global using System.IO;
global using ContextMenu = System.Windows.Controls.ContextMenu;
global using MenuItem = System.Windows.Controls.MenuItem;
global using Application = System.Windows.Application;
global using UserControl = System.Windows.Controls.UserControl;
global using Color = System.Windows.Media.Color;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using TextBox = System.Windows.Controls.TextBox;
global using Size = System.Windows.Size;
global using Point = System.Windows.Point;
global using Button = System.Windows.Controls.Button;
global using MessageBox = System.Windows.MessageBox;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Orientation = System.Windows.Controls.Orientation;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using Cursors = System.Windows.Input.Cursors;
